# basic options
title: SomAkari blog
author: Somval
email: somval@protonmail.com
description: Diseñadora gráfica + diseñadora web + artista + autodidacta.
url: https://somakari.com/blog/
enforce_ssl: somakari.com/blog/

twitter_username: Som_Akari
github_username: somval
title_image: "https://somakari.com/img/moon.png"
# google_analytics: UA-12345678-1 / "UA_123456_1" 

header_pages:
  - about.md
  - now.md

# Build settings
markdown: kramdown
theme: minima

# Plugins
plugins:
  - jemoji
  - jekyll-feed
