# basic options
title: Somval blog
author: Somval
email: somval@protonmail.com
description: Amante del diseño web y gráfico, así como del marketing online y las redes sociales. Apasionada de la naturaleza, la música, el deporte y el desarrollo personal. Aprendiendo algo nuevo cada día.
twitter_username: somvalprints
github_username: somval

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- now.html
- about.html

# Build settings
markdown: kramdown
theme: minima
