# basic options
title: New-awesome-blog
author: Somval
email: your-email@domain.com
description: A wonderful blog
twitter_username: somvalprints
github_username: somval

# Build settings
markdown: kramdown
theme: minima
