# basic options
title: Gilfinart blog
author: Somval
email: somval@protonmail.com
description: Diseñadora gráfica + diseñadora web + artista + autodidacta.
url: https://gilfinart.com/blog/
enforce_ssl: gilfinart.com/blog/

twitter_username: somvalprints
github_username: somval
title_image: "https://gilfinart.com/img/moon.png"
# google_analytics: UA-12345678-1 / "UA_123456_1" 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima

# Plugins
plugins:
  - jemoji
