# basic options
title: Somval blog
author: Somval
email: somval@protonmail.com
description: A wonderful blog
twitter_username: somvalprints
github_username: somval

# Build settings
markdown: kramdown
theme: minima
