# basic options
title: Gilfinart blog
author: Somval
email: somval@protonmail.com
description: Amante del diseño web y gráfico, así como del marketing online. Apasionada de la naturaleza, la música y el desarrollo personal. Aprendiendo algo nuevo cada día.
url: https://gilfinart.com/blog/
enforce_ssl: gilfinart.com/blog/

twitter_username: somvalprints
github_username: somval
title_image: "https://gilfinart.com/img/moon.png"
# google_analytics: UA-12345678-1 / "UA_123456_1" 

# Build settings
markdown: kramdown
theme: minima

# Plugins
plugins:
  - jemoji
