# basic options
title: Somval blog
author: Somval
email: somval@protonmail.com
description: Amante del diseño web y gráfico, así como del marketing online y las redes sociales. Programadora WordPress. Curiosa. Apasionada de la naturaleza, la música, el deporte y el desarrollo personal. Aprendiendo algo nuevo cada día.
twitter_username: somvalprints
github_username: somval

# Build settings
markdown: kramdown
theme: minima
