# basic options
title: Somval blog
author: Somval
email: somval@protonmail.com
description: Amante del diseño web y gráfico, así como del marketing online. Apasionada de la naturaleza, la música y el desarrollo personal. Aprendiendo algo nuevo cada día.
 
twitter_username: somvalprints
github_username: somval

# google_analytics:

# Build settings
markdown: kramdown
theme: minima
